# Test directory.
my $test_dir = "$ENV{'PWD'}/t/TagReaderPerl";

print "Testing: Tags example.\n" if $debug;
my $obj = $class->new;
$obj->set_file($test_dir.'/data/tag1.tags');
my @tag = $obj->gettoken;
ok($tag[0], "<text>");
ok($tag[1], "text");
ok($tag[2], 1);
ok($tag[3], 1);
@tag = $obj->gettoken;
ok($tag[0], 'text');
ok($tag[1], 'data');
ok($tag[2], 1);
ok($tag[3], 7);
@tag = $obj->gettoken;
ok($tag[0], '</text>');
ok($tag[1], '/text');
ok($tag[2], 1);
ok($tag[3], 11);
@tag = $obj->gettoken;
ok($tag[0], "\n");
ok($tag[1], 'data');
ok($tag[2], 1);
ok($tag[3], 18);

$obj = $class->new;
$obj->set_file($test_dir.'/data/tag2.tags');
@tag = $obj->gettoken;
ok($tag[0], "<text:color>");
ok($tag[1], "text:color");
ok($tag[2], 1);
ok($tag[3], 1);
@tag = $obj->gettoken;
ok($tag[0], 'text');
ok($tag[1], 'data');
ok($tag[2], 1);
ok($tag[3], 13);
@tag = $obj->gettoken;
ok($tag[0], '</text:color>');
ok($tag[1], '/text:color');
ok($tag[2], 1);
ok($tag[3], 17);
@tag = $obj->gettoken;
ok($tag[0], "\n");
ok($tag[1], 'data');
ok($tag[2], 1);
ok($tag[3], 30);

$obj = $class->new;
$obj->set_file($test_dir.'/data/tag3.tags');
@tag = $obj->gettoken;
ok($tag[0], "<text>");
ok($tag[1], "text");
ok($tag[2], 1);
ok($tag[3], 1);
@tag = $obj->gettoken;
ok($tag[0], '<![CDATA[<text>text</text>]]>');
ok($tag[1], '![cdata[');
ok($tag[2], 1);
ok($tag[3], 7);
@tag = $obj->gettoken;
ok($tag[0], '</text>');
ok($tag[1], '/text');
ok($tag[2], 1);
ok($tag[3], 36);
@tag = $obj->gettoken;
ok($tag[0], "\n");
ok($tag[1], 'data');
ok($tag[2], 1);
ok($tag[3], 43);

$obj = $class->new;
$obj->set_file($test_dir.'/data/tag4.tags');
@tag = $obj->gettoken;
ok($tag[0], "<x>");
ok($tag[1], "x");
ok($tag[2], 1);
ok($tag[3], 1);
@tag = $obj->gettoken;
ok($tag[0], '<![CDATA[a<x>b]]]>');
ok($tag[1], '![cdata[a');
ok($tag[2], 1);
ok($tag[3], 4);
@tag = $obj->gettoken;
ok($tag[0], '</x>');
ok($tag[1], '/x');
ok($tag[2], 1);
ok($tag[3], 22);
@tag = $obj->gettoken;
ok($tag[0], "\n");
ok($tag[1], 'data');
ok($tag[2], 1);
ok($tag[3], 26);
